BOARD := "nucleo_h723zg"
BUILD_DIR := "build"

# Cross-compatible way to call west from inside a project directory
WEST := if os_family() == "windows" { "..\\..\\.venv\\Scripts\\python.exe -m west" } else { "../../.venv/bin/python -m west" }
set shell := ["sh", "-c"]
set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

default: build

build:
    {{WEST}} build -b {{BOARD}} -p auto -d {{BUILD_DIR}}

flash:
    {{WEST}} flash -d {{BUILD_DIR}}

# Run arbitrary west commands
west ARGS:
    {{WEST}} {{ARGS}}